name: delivery_express
description: Delivery Express is a mobile application that connects couriers to customers.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter_colorpicker: ^1.0.3
  cupertino_icons: ^1.0.2
  equatable: ^2.0.3
  firebase_auth: ^3.3.9
  firebase_core: ^1.13.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^1.0.3
  get: ^4.6.1
  intl: ^0.17.0
  mask_text_input_formatter: ^2.1.0
  provider: ^6.0.2
  cloud_firestore: ^3.1.17
  dropdown_button2: ^1.6.2
  flutter_switch: ^0.3.2
  flutter_native_splash: ^2.2.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
    - lib/ui/assets/images/svg/
    - lib/ui/assets/images/png/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  fonts:
    - family: Montserrat
      fonts:
        - asset: lib/ui/assets/fonts/Montserrat-Light.ttf
          weight: 300
        - asset: lib/ui/assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: lib/ui/assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: lib/ui/assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: lib/ui/assets/fonts/Montserrat-Bold.ttf
          weight: 700

flutter_icons:
  ios: true
  android: true
  image_path_android: assets/logo/DeliveyExpressLogo.png
  image_path_ios: assets/logo/DeliveyExpressLogo.png
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: assets/logo/DeliveyExpressLogoForeground.png
# flutter_intl:
#   enabled: true
