package com.pmalaquias.deliveryexpress.domain.service

import com.pmalaquias.deliveryexpress.domain.entities.User
import com.pmalaquias.deliveryexpress.domain.repositories.IUserRepository

/**
 * Class for the Authentication Service.
 *
 * This class provides methods for user login and registration.
 *
 * @property userRepository The repository of the user.
 *
 * @function login Authenticates a user with their email and password.
 * @param email The email of the user.
 * @param password The password of the user.
 * @return The authenticated user if the email and password match, null otherwise.
 *
 * @function register Registers a new user with their name, email, and password.
 * @param nome The name of the user.
 * @param email The email of the user.
 * @param password The password of the user.
 * @return The newly registered user.
 */
class AuthenticationService(private val userRepository: IUserRepository) {

    fun login(email: String, password: String): User? {
        val user = userRepository.getUserByEmail(email) ?: return null
        return if (user.password == password) user else null
    }

    fun register(nome: String, email: String, password: String): User {
        val newUser = User(id = 0L, name = nome, email = email, password = password) // id = 0L because it will be generated by the database
        userRepository.saveUser(newUser)
        return newUser
    }
}